FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as build

RUN microdnf update -y --nodocs && microdnf install ca-certificates -y --nodocs

FROM registry.access.redhat.com/ubi9/ubi-micro:latest

ARG TAG

LABEL name="MinIO Gateway Controller" \
      vendor="MinIO Inc <dev@min.io>" \
      maintainer="MinIO Inc <dev@min.io>" \
      version="${TAG}" \
      release="${TAG}" \
      summary="MinIO Gateway Controller provides dynamic Envoy configuration for MinIO Tenants." \
      description="Gateway Controller watches MinIO Tenant resources and generates Envoy xDS configuration for dynamic load balancing and routing."

COPY --from=build /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/pki/ca-trust/extracted/pem/

COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE

COPY dist/gateway-controller-linux-amd64 /gateway-controller

ENTRYPOINT ["/gateway-controller"]